USE CollapseAssistance; /*RICARDO*/


DELIMITER ||
DROP TRIGGER IF EXISTS TRIGGER_BEFORE_IN_Dias_No_Laborales ||
 CREATE TRIGGER TRIGGER_BEFORE_IN_Dias_No_Laborales BEFORE INSERT ON Dias_No_Laborales
 FOR EACH ROW
 BEGIN
 SET NEW.Modifico_Usuario = SUBSTRING(CURRENT_USER(),1,10);
 SET NEW.Fecha_Modificacion = CURRENT_DATE();
 END
||


DELIMITER ||

DROP TRIGGER IF EXISTS TRIGGER_BEFORE_UP_Dias_No_Laborales ||
CREATE TRIGGER TRIGGER_BEFORE_UP_Dias_No_Laborales BEFORE UPDATE ON Dias_No_Laborales
FOR EACH ROW
BEGIN
SET NEW.Modifico_Usuario = SUBSTRING(CURRENT_USER(),1,10);
SET NEW.Fecha_Modificacion = CURRENT_DATE();
END

||
