USE CollapseAssistance; /*RICARDO*/

DELIMITER ||
DROP TRIGGER IF EXISTS TRIGGER_BEFORE_IN_Empleados ||
 CREATE TRIGGER TRIGGER_BEFORE_IN_Empleados BEFORE INSERT ON Empleados
 FOR EACH ROW
 BEGIN
        SET NEW.Inserto_Usuario = SUBSTRING(CURRENT_USER(),1,10);
         SET NEW.Fecha_Insercion = CURRENT_DATE();
 END||





DELIMITER ||
DROP TRIGGER IF EXISTS TRIGGER_BEFORE_UP_Empleados ||
 CREATE TRIGGER TRIGGER_BEFORE_UP_Empleados BEFORE INSERT ON Empleados
 FOR EACH ROW
 BEGIN
 SET NEW.Modifico_Usuario = SUBSTRING(CURRENT_USER(),1,10);
 SET NEW.Fecha_Modificacion = CURRENT_DATE();
 END



||
