USE CollapseAssistance;

DELIMITER ||
DROP TRIGGER IF EXISTS TRIGGER_BEFORE_INSERT_Horarios ||
 CREATE TRIGGER TRIGGER_BEFORE_INSERT_Horarios BEFORE INSERT ON Horarios
 FOR EACH ROW
 BEGIN
 SET NEW.Inserto_Usuario  = SUBSTRING(CURRENT_USER(),1,10);
 SET NEW.Fecha_Insercion = CURRENT_DATE();
 END

||
