USE CollapseAssistance; /*Grisell*/

DELIMITER ||

DROP TRIGGER IF EXISTS TRIGGER_BEFORE_INSERT_INCIDENCIAS_EMPLEADOS ||
CREATE TRIGGER TRIGGER_BEFORE_INSERT_INCIDENCIAS_EMPLEADOS BEFORE INSERT ON Incidencias_Empleados
FOR EACH ROW
BEGIN
SET NEW.Inserto_Usuario = SUBSTRING(CURRENT_USER(),1,10);
SET NEW.Fecha_Insercion = CURRENT_DATE();
END

||

DELIMITER ||

DROP TRIGGER IF EXISTS TRIGGER_BEFORE_UPDATE_INCIDENCIAS_EMPLEADOS ||
CREATE TRIGGER TRIGGER_BEFORE_UPDATE_INCIDENCIAS_EMPLEADOS BEFORE UPDATE ON Incidencias_Empleados
FOR EACH ROW
BEGIN
SET NEW.Modifico_Usuario = SUBSTRING(CURRENT_USER(),1,10);
SET NEW.Fecha_Modificacion = CURRENT_DATE();
END

||
