USE CollapseAssistance;

--Insertar estado en tablas de estado (Sin este no prodrá hacer el registro en la tabla de municipios. Ejecutar una vez)
INSERT INTO Estados_Pais (ID_Estado, Nombre_Estado) VALUES (01, "Aguascalientes"),
                                                            (02, "Baja California"),
                                                            (03, "Baja California Sur"),
                                                            (04, "Campeche"),
                                                            (05, "Cohuila"),
                                                            (06, "Colima"),
                                                            (07, "Chiapas"),
                                                            (08, "Chihuahua"),
                                                            (09, "Durango"),
                                                            (10, "CDMX"),
                                                            (11, "Guanajuato"),
                                                            (12, "Guerrero"),
                                                            (13, "Hidalgo"),
                                                            (14, "Jalisco"),
                                                            (15, "Estado de México"),
                                                            (16, "Michoacán"),
                                                            (17, "Morelos"),
                                                            (18, "Nayarit"),
                                                            (19, "Nuevo León"),
                                                            (20, "Oaxaca"),
                                                            (21, "Puebla"),
                                                            (22, "Querétaro"),
                                                            (23, "Quintana Roo"),
                                                            (24, "San Luis Potosí"),
                                                            (25, "Sinaloa"),
                                                            (26, "Sonora"),
                                                            (27, "Tabasco"),
                                                            (28, "Tamaulipas"),
                                                            (29, "Tlaxcala"),
                                                            (30, "Veracruz"),
                                                            (31, "Yucatán"),
                                                            (32, "Zacatecas");

SELECT * FROM Municipios_Estados;
